#!/usr/bin/env sh

# Fonts
ic_font="JetBrainsMono Nerd Font"
text_font="SF UI Text"

# Colors
# white='C3BAC6' # Gray 2
white='988BA2'   # Gray 1
black='1F1E2F'
green='ABE9B3'
purple='C9CBFF'
blue='96CDFB'

spacebar -m config position                    bottom
spacebar -m config display                     main
spacebar -m config height                      32
spacebar -m config title                       on
spacebar -m config spaces                      on
spacebar -m config clock                       on
spacebar -m config power                       on
spacebar -m config padding_left                15
spacebar -m config padding_right               15
spacebar -m config spacing_left                25
spacebar -m config spacing_right               20
spacebar -m config text_font                   "$text_font:Light:14.0"
spacebar -m config icon_font                   "$ic_font:Regular:14.0"
spacebar -m config background_color            0xff$black
spacebar -m config foreground_color            0xff$white
spacebar -m config power_icon_color            0xff$green
spacebar -m config battery_icon_color          0xff$white
spacebar -m config dnd_icon_color              0xff$purple
spacebar -m config clock_icon_color            0xff$white
spacebar -m config power_icon_strip               #  
spacebar -m config space_icon                   # •
spacebar -m config space_icon_color            0xff$blue
spacebar -m config space_icon_color_secondary  0xff78c4d4
spacebar -m config space_icon_color_tertiary   0xfffff9b0
spacebar -m config space_icon_strip            1 2 3 4 5 6 7 8 9 10 # 一 二 三 四 五 六 七 八 九 十
spacebar -m config spaces_for_all_displays     on
spacebar -m config clock_icon                  
spacebar -m config dnd_icon                    
spacebar -m config clock_format                "%R  %d/%m" # "%d/%m/%y %R"
spacebar -m config right_shell                 off
spacebar -m config right_shell_icon            
spacebar -m config right_shell_command         "whoami"

echo "spacebar configuration loaded.."
